const electionAreasToSeats = {
    "Adana": 15,
    "Adıyaman": 5,
    "Afyonkarahisar": 6,
    "Ağrı": 4,
    "Aksaray": 4,
    "Amasya": 3,
    "Ankara (I)": 13,
    "Ankara (II)": 11,
    "Ankara (III)": 12,
    "Antalya": 17,
    "Ardahan": 2,
    "Artvin": 2,
    "Aydın": 8,
    "Balıkesir": 9,
    "Bartın": 2,
    "Batman": 5,
    "Bayburt": 1,
    "Bilecik": 2,
    "Bingöl": 3,
    "Bitlis": 3,
    "Bolu": 3,
    "Burdur": 3,
    "Bursa (I)": 10,
    "Bursa (II)": 10,
    "Çanakkale": 4,
    "Çankırı": 2,
    "Çorum": 4,
    "Denizli": 7,
    "Diyarbakır": 12,
    "Düzce": 3,
    "Edirne": 4,
    "Elazığ": 5,
    "Erzincan": 2,
    "Erzurum": 6,
    "Eskişehir": 6,
    "Gaziantep": 14,
    "Giresun": 4,
    "Gümüşhane": 2,
    "Hakkâri": 3,
    "Hatay": 11,
    "Iğdır": 2,
    "Isparta": 4,
    "İstanbul (I)": 35,
    "İstanbul (II)": 27,
    "İstanbul (III)": 36,
    "İzmir (I)": 14,
    "İzmir (II)": 14,
    "Kahramanmaraş": 8,
    "Kars": 3,
    "Kastamonu": 3,
    "Karabük": 3,
    "Karaman": 3,
    "Kayseri": 10,
    "Kırıkkale": 3,
    "Kırklareli": 3,
    "Kırşehir": 2,
    "Kilis": 2,
    "Kocaeli": 14,
    "Konya": 15,
    "Kütahya": 5,
    "Malatya": 6,
    "Manisa": 10,
    "Mardin": 6,
    "Mersin": 13,
    "Muğla": 7,
    "Muş": 3,
    "Nevşehir": 3,
    "Niğde": 3,
    "Ordu": 6,
    "Osmaniye": 4,
    "Rize": 3,
    "Sakarya": 8,
    "Samsun": 9,
    "Siirt": 3,
    "Sinop": 2,
    "Sivas": 5,
    "Şanlıurfa": 14,
    "Şırnak": 4,
    "Tekirdağ": 8,
    "Tokat": 5,
    "Trabzon": 6,
    "Tunceli": 1,
    "Uşak": 3,
    "Van": 8,
    "Yalova": 3,
    "Yozgat": 4,
    "Zonguldak": 5
}

const getSeatsById = (id) => {
    const values = Object.values(electionAreasToSeats);
    return values[id-1];
}

const getIdByAreaName = (electionEnvironment) => {
    const keys = Object.keys(electionAreasToSeats);
    return keys.indexOf(electionEnvironment) + 1;
}

export {
    electionAreasToSeats,
    getSeatsById,
    getIdByAreaName,
}